on:
  push:
    branches:
      - test
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: simple
          version-file: "src/manifest.json"
      - name: Show output from Release-Please
        run: |
          echo "release_created: ${{ steps.release.outputs.* }}"
          echo "release_created: ${{ steps.release.outputs.release_created }}"
          echo "upload_url: ${{ steps.release.outputs.upload_url }}"
          echo "html_url: ${{ steps.release.outputs.html_url }}"
          echo "tag_name: ${{ steps.release.outputs.tag_name }}"
          echo "major: ${{ steps.release.outputs.major }}"
          echo "minor: ${{ steps.release.outputs.minor }}"
          echo "patch: ${{ steps.release.outputs.patch }}"
      - id: step1
        run: echo "::set-output name=test::hello"
      - id: step2
        run: echo "::set-output name=test::world"
      - name: Display
        run: |
          echo "Step 1 test: ${{ steps.step1.outputs.test }}"
          echo "Step 2 test: ${{ steps.step2.outputs.test }}"
        if: ${{ steps.release.outputs.release_created }}
